user_name: felipemkautzmann@gmail.com
client_theme: databricks_vatenfall


catalog: vatenfall_dev


schemas: 
  raw: raw
  refined: refined
  analytics: analytics


volumes:
  landing: landing
  checkpoint: checkpoint


landing:
  market_prices: market_prices
  weather: weather
  grid_events: grid_events
  references: references


checkpoint:
  market_prices: market_prices
  weather: weather
  grid_events: grid_events
  references: references


tables:
  bronze:
    market_prices: market_prices
    weather: weather
    grid_events: grid_events
    references: references

